INSERT INTO T_CURSOR(StudentID, prenom,nom,note, etat, remarque) VALUES ('1','AYOTTE', 'Victor H. O.','100','Admis','') 	
INSERT INTO T_CURSOR (StudentID, prenom,nom,note, etat, remarque) VALUES ('2','CALO','Fabrizio','','Abandon','')	
INSERT INTO T_CURSOR (StudentID, prenom,nom,note, etat, remarque) VALUES ('3','CLARAT','Arnaud D, J.','','Ajourné','Laboratoire: initiation aux bases de données')
INSERT INTO T_CURSOR (StudentID, prenom,nom,note, etat, remarque) VALUES ('4','COUTELLE','Julien P','','Abandon','') 	
INSERT INTO T_CURSOR (StudentID, prenom,nom,note, etat, remarque) VALUES ('5','CUGNON','Geoffrey G','79','Admis','' )	
INSERT INTO T_CURSOR (StudentID, prenom,nom,note, etat, remarque) VALUES  ('6','DECUYPERE','Jules H, L.','82','Admis','' )	
INSERT INTO T_CURSOR (StudentID, prenom,nom,note, etat, remarque) VALUES  ('7','DEVRESSE', 'Cindy G, R.','64','Admise','' )	
INSERT INTO T_CURSOR (StudentID, prenom,nom,note, etat, remarque) VALUES  ('8','DONGMO', 'Christian O','61','Admis','' )	
INSERT INTO T_CURSOR (StudentID, prenom,nom,note, etat, remarque) VALUES  ('9','FRANÇOIS','Shantou','57','Admis','' )	
INSERT INTO T_CURSOR (StudentID, prenom,nom,note, etat, remarque) VALUES  ('10','GENICOT','Jerôme','100','Admis',''	)
INSERT INTO T_CURSOR  (StudentID, prenom,nom,note, etat, remarque) VALUES  ('11','GOEFFOET','Guillaume A, R.','','Abandon','' )	
INSERT INTO T_CURSOR (StudentID, prenom,nom,note, etat, remarque) VALUES   ('12','GORLIER','Laurent A, R.','93','Admis','')
INSERT INTO T_CURSOR (StudentID, prenom,nom,note, etat, remarque) VALUES   ('13','KOUAKOU','Victoria S, A.','','Abandon','' 	)
INSERT INTO T_CURSOR (StudentID, prenom,nom,note, etat, remarque) VALUES  ('14','LETAWE','Isabelle G, E.','57','Admise','')
INSERT INTO T_CURSOR (StudentID, prenom,nom,note, etat, remarque) VALUES   ('15','LEVIS','Maxime C, V.','100','Admis','')
INSERT INTO T_CURSOR (StudentID, prenom,nom,note, etat, remarque) VALUES  ('16','MOHIMONT','Gauthier C','93','Admis','')
INSERT INTO T_CURSOR  (StudentID, prenom,nom,note, etat, remarque) VALUES  ('17','MOREIRA GUEDES','Carlos F','100','Admis','')
INSERT INTO T_CURSOR (StudentID, prenom,nom,note, etat, remarque) VALUES   ('18','OUAHIB','Anyssa N','99','Admise','')
INSERT INTO T_CURSOR (StudentID, prenom,nom,note, etat, remarque) VALUES  ('19','PIERRE','Korenthin P, I.','75','Admis','')
INSERT INTO T_CURSOR (StudentID, prenom,nom,note, etat, remarque) VALUES  ('20','PRINCE','Maxime V, D.','','Ajourné','Laboratoire: initiation aux bases de données')
INSERT INTO T_CURSOR (StudentID, prenom,nom,note, etat, remarque) VALUES  ('21','SANTOS CRISTOVAO',' Antonio J','57','Admis',''	)
INSERT INTO T_CURSOR (StudentID, prenom,nom,note, etat, remarque) VALUES ('22','SIDIME','Fode B.','' ,'Abandon','' 	)
INSERT INTO T_CURSOR  (StudentID, prenom,nom,note, etat, remarque) VALUES  ('23','TORFS','Corentin E, N.','99','Admis','')